const stages = [
  {
    id:'phase1',label:'Phase 1',sub:'Top of Pipeline + Academy Build',color:'#22d3ee',glow:'rgba(34,211,238,.09)',
    summary:'Build the attention engine and create the product at the same time: The $1 Million Idea Search, PM in the AM, the man-on-the-street contest videos, and the EM:Dirt academy. Then build the guide, worksheets, Pocket AI, and implementation path backward from the finished teaching experience.',
    nodes:[
      {title:'Build The $1 Million Idea Search',sub:'Free contest, founder stories, sponsors, and the reality-show engine.',icon:'camera',simple:'Create the campaign, casting system, landing pages, sponsor package, and founder-story format that Phase 2 will use to search Chicagoland for businesses with a potential $1 million idea.',bullets:['Part One captures the founder, business, opportunity, and blockage.','Part Two returns after support to show what was actually used and what changed.','Designed for lead generation, B2B sponsorships, retargeting, and a year-long finalist pipeline.'],perry:'Authority, selected interviews, standards, and final winner selection.',team:'Campaign design, casting, production, editing, distribution, sponsor packaging, lead capture, and applicant routing.',feeds:'Phase 2 search ads, EM:Dirt retargeting, T1C, diagnostics, and finalists.'},
      {title:'Produce “Do You Have a Million Dollar Business?” Interviews',sub:'Man-on-the-street contest content bank for Phase 2.',icon:'camera',simple:'Film the public-facing street and founder interviews during Phase 1 so Phase 2 can release them consistently while the free search campaign is running.',bullets:['Short, arresting questions built for social distribution.','A younger co-host or spokesperson creates frequency and approachability.','Every video routes viewers into the free $1 Million Idea Search.'],perry:'Approves the framing and appears selectively where his authority adds leverage.',team:'Location planning, releases, interviewing, filming, editing, captions, distribution calendar, and calls to action.',feeds:'Phase 2 lead generation, waitlist growth, sponsors, and EM:Dirt retargeting.'},
      {title:'PM in the AM',sub:'Weekly public authority and bottleneck-solving show.',icon:'mic',simple:'Perry anchors the idea; the team creates the frequency, packaging, clips, calls to action, and follow-up system.',bullets:['Weekly public podcast and video show.','One signal, one lesson, one behavior.','Designed to route people into the search, EM:Dirt, the diagnostic, community, and sponsors.'],perry:'High-leverage teaching, selected conversations, and intellectual authority.',team:'Research, production, editing, posting, repurposing, email/text distribution, and measurement.',feeds:'Phase 2 search, EM:Dirt, Monday Morning Leadership, Tier 2, community, and sponsors.'},
      {title:'Create the EM:Dirt Academy Videos',sub:'Teach first. Build the guide backward from the real product.',icon:'book',simple:'Record the academy Perry actually wants to deliver, then convert the teaching into the guide, worksheets, Pocket AI context, milestones, and the 90-day daily-practice experience.',bullets:['Entrepreneur Manure stays in the title as a qualification filter.','Target owners willing to roll up their sleeves, niche down, test content, ads, AI, Reddit, and practical growth routes.','Central proof metaphor: plants need fertilizer; businesses do too.'],perry:'Core principles, stories, examples, and the “Perry enough” point of view.',team:'Curriculum design, shoot plan, recording, edit, worksheets, Pocket AI, platform, and implementation sequence.',feeds:'Phase 2 beta and retargeting, T1A public product, and content campaigns.'},
      {title:'Reface Content, Social, Web & Data Capture',sub:'Build the modern front door and six months of usable content.',icon:'browser',simple:'Rebuild the public journey so every episode, clip, application, contest video, and event has a measurable next step.',bullets:['Homepage, landing pages, social positioning, email/SMS capture, segmentation, retargeting, and attribution.','Home recording rig and spokesperson workflow.','Six months of foundational content banked during the initial build.'],perry:'Approves voice, positioning, and key content moments.',team:'Design, development, CRM, automations, analytics, publishing, and campaign operations.',feeds:'Phase 2 search campaign and every tier after it.'}
    ]
  },
  {
    id:'phase2',label:'Phase 2',sub:'3-Month Search + EM:Dirt Beta',color:'#fbbf24',glow:'rgba(251,191,36,.09)',
    summary:'Run the free $1 Million Idea Search across Chicagoland for three months, release the contest videos produced in Phase 1, look for 10 business owners with credible $1 million potential, and retarget the full lead pool with EM:Dirt as the feeder offer.',
    nodes:[
      {title:'Run the Free $1 Million Idea Search',sub:'Three months of ads, applications, and lead-generation testing.',icon:'chart',beta:true,track:['Month 1<br>Launch','Month 2<br>Optimize','Month 3<br>Select 10','Retarget<br>EM:Dirt'],betaNote:'Phase 2 is the three-month search and beta-acquisition campaign. Tier 2 is a separate permanent offer containing the diagnostic and SOS Business Operating System.',simple:'Use the free contest as the top-of-funnel reason for Chicagoland owners to raise their hands. Measure how many leads, applications, and qualified businesses the search can produce.',bullets:['Run paid and organic search campaigns for three months.','Test audience, message, creative, channel, cost per lead, and application quality.','Use a younger spokesperson and Perry’s authority together.'],perry:'Authority, selected campaign appearances, and standards for what qualifies as a serious idea.',team:'Ads, landing pages, lead capture, applicant communication, optimization, tracking, and reporting.',feeds:'10 selected businesses, EM:Dirt retargeting, T1C prospects, diagnostics, sponsors, and finalist stories.'},
      {title:'Release the Phase 1 Contest Videos',sub:'Publish “Do You Have a Million Dollar Business?” interviews throughout the search.',icon:'camera',simple:'Release the pre-produced man-on-the-street and founder videos as the campaign’s attention engine rather than waiting to create content after the ads begin.',bullets:['Use clips as paid ads, organic posts, email content, and sponsor inventory.','Rotate questions, founders, niches, and bottlenecks to discover what earns attention.','Every release drives to the free search application.'],perry:'Selected reactions, authority clips, and final framing.',team:'Publishing cadence, ad variants, retargeting audiences, captions, distribution, and performance analysis.',feeds:'Search leads, application volume, EM:Dirt audiences, and PM in the AM.'},
      {title:'Find 10 Chicagoland Business Owners',sub:'The first visible proof cohort.',icon:'users',simple:'Identify 10 owners who believe they have a potential $1 million idea or business and who are willing to implement, document the process, and provide meaningful feedback.',bullets:['Selection balances opportunity, story, coachability, and willingness to do the work.','The 10 create concrete stories rather than an anonymous course beta.','Participation can expose service, diagnostic, and SOS needs.'],perry:'Sets the quality standard and participates in selected founder moments.',team:'Screening, interviews, selection, onboarding, communication, tracking, and documentation.',feeds:'EM:Dirt proof, case studies, T1C, Tier 2 diagnostic, SOS, and Million Dollar Idea finalists.'},
      {title:'Retarget the Lead Pool With EM:Dirt',sub:'The free contest becomes the feeder program.',icon:'book',simple:'Everyone who engages with the search does not need to win. Qualified applicants and viewers are retargeted with the $297 EM:Dirt offer as the practical next step they can begin now.',bullets:['Segment applicants, video viewers, site visitors, and incomplete applications.','Use the search question to make the EM:Dirt offer personally relevant.','Track conversion from free contest lead to paid accelerator customer.'],perry:'Provides the core promise and authority behind the invitation.',team:'Retargeting, email/SMS follow-up, sales pages, checkout, onboarding, support, and conversion analysis.',feeds:'T1A customers, Farm members, T1C opportunities, diagnostics, and SOS.'},
      {title:'Validate EM:Dirt Through Real Use',sub:'Use the selected businesses to improve the product while the campaign builds demand.',icon:'activity',simple:'The selected beta businesses use the academy, guide, prompts, and Pocket AI so the team can document what creates action, what creates friction, and what must improve before larger scale.',bullets:['Track baseline, implementation behavior, questions, and observable results.','Capture proof content without overpromising outcomes.','Revise the academy and feeder sequence based on real use.'],perry:'Reviews key proof and confirms whether the experience remains Perry enough.',team:'Facilitation, usage tracking, interviews, revisions, case-study production, and launch recommendation.',feeds:'Improved T1A, public conversion proof, T1C, Tier 2, and future contest seasons.'}
    ]
  },
  {id:'tier1',label:'Tier 1',sub:'Activation, Community & Services',color:'#22d3ee',glow:'rgba(34,211,238,.08)',summary:'Three practical entry points: use the accelerator, join the Chicago community, or hire the team. This creates a large pool without forcing Perry to personally fulfill the fundamentals.',nodes:[
    {title:'T1A — Entrepreneur Manure / EM:Dirt',sub:'$297 • 90-day DIY accelerator.',icon:'book',simple:'Video academy, worksheets, daily practice, and Pocket AI trained on Perry’s books and the participant’s context to quiet operational chaos and install a useful change.',bullets:['Core fundamentals remixed into a practical 90-day rhythm.','Milestones reward implementation rather than passive viewing.','Phase 2 validates the offer and uses the free search as its feeder program.'],perry:'Creates the source material and approves the final standard.',team:'Runs the academy, AI, support, prompts, milestones, onboarding, and reporting.',feeds:'Farm membership, T1C, the Tier 2 diagnostic, and SOS.'},
    {title:'T1B — The Farm Community & Events',sub:'Approximately $500/year • Chicago first.',icon:'users',simple:'A 200+ member Chicago community that creates net worth for one another through fun plus function—not boring networking.',bullets:['Improv, axe throwing, dinners, workshops, collaborative problem solving, and local activations.','Membership supports community infrastructure; event tickets and sponsors support individual events.','Event ticket revenue belongs to Perry.'],perry:'Selected appearances and cultural authority.',team:'Programming, venues, logistics, community systems, follow-up, content capture, and member progression.',feeds:'Diagnostics, SOS, T1C, Farm Builders, sponsors, and future chapters.'},
    {title:'T1C — Top-to-Bottom Business Solutions',sub:'Powered by Perry Marshall • fulfilled by IRL, Chicago AMP & 79ratio.',icon:'tools',simple:'White-labeled branding, media, automation, AI agents, websites, funnels, advertising, and business implementation. Perry receives an agreed direct kickback or revenue share.',bullets:['Simple content and ad programs can create major gains in the right niches.','Services convert advice into installed systems and case studies.','Calculator uses an estimated $2,500 Perry kickback per client—not total project revenue.'],perry:'Brand authority and agreed Powered by Perry positioning.',team:'Sales, scoping, production, fulfillment, vendors, reporting, and customer success.',feeds:'Implementation proof, recurring services, SOS, diagnostics, and Million Dollar Idea stories.'}
  ]},
  {id:'tier2',label:'Tier 2',sub:'Diagnostic + Business Operating System',color:'#fbbf24',glow:'rgba(251,191,36,.08)',summary:'Tier 2 is not Phase 2. It is the permanent diagnostic and software layer: identify the real operational bottleneck, then use SOS as a Business Operating System that increasingly runs mundane functions, tracks activity, and improves onboarding.',nodes:[
    {title:'Perry’s Custom Diagnostic Tool',sub:'Approximately $497 • finds the real operational bottleneck.',icon:'chart',simple:'A diagnostic and interpretation process that identifies what is actually choking growth and routes the owner into the right next move.',bullets:['Primary bottleneck—not twenty random recommendations.','High-margin Perry revenue with mentor, administration, and support costs.','Qualification tool for services, SOS, Farm Builders, and premium access.'],perry:'Diagnostic philosophy, standards, and occasional high-level interpretation.',team:'Assessment system, mentor call, report, routing, follow-up, and measurement.',feeds:'T1C, SOS, Tier 3, premium Perry, and Million Dollar Idea.'},
    {title:'SOS Founding Year',sub:'$97 for the first year • Business Operating System, not merely a CRM.',icon:'cpu',simple:'SOS is designed to become the operating layer that handles and coordinates mundane business functions, improves tracking, and makes employee and customer onboarding more dependable.',bullets:['Founding users can renew at a modestly increased rate.','Tracks people, tasks, pipelines, communication, onboarding, workflows, and automations in one operating environment.','Over time, AI and automation can run more repetitive business functions instead of merely storing contacts.','Identifies members who want the deeper Tier 3 builder experience.'],perry:'Provides the business principles and authority behind the system.',team:'Builds product, onboarding, support, workflows, automations, analytics, and renewal paths.',feeds:'Tier 3 SOS Builder, custom AI agents, diagnostics, T1C, and Farm Builders.'}
  ]},
  {id:'tier3',label:'Tier 3',sub:'SOS Builder + Farm Builders',color:'#8b5cf6',glow:'rgba(139,92,246,.1)',summary:'The $297/month builder tier combines advanced SOS, a custom onboarding AI agent, the development community, and a path from power user to ecosystem leader.',nodes:[
    {title:'SOS Builder Membership',sub:'$297/month • advanced software + dev community.',icon:'cpu',simple:'Members upgrade into an active co-building environment where they use advanced SOS features and help shape reusable workflows for the wider ecosystem.',bullets:['Advanced software and direct access to the development community.','Custom items built around real member workflows may become reusable ecosystem features.','Contributors receive recognition or payback such as credits, free months, priority, status, or preferred support.'],perry:'High-level principles and occasional authority moments.',team:'Roadmap, development, feature testing, support, community, documentation, and contributor rewards.',feeds:'Custom AI agent, Farm Builders, Enterprise workflows, and premium access.'},
    {title:'Custom Onboarding AI Agent',sub:'Built for the member’s automation and onboarding process.',icon:'bot',simple:'Each Tier 3 member receives a custom AI agent focused on automating or improving a meaningful part of their onboarding workflow.',bullets:['Maps the current onboarding process and identifies repetitive steps.','Builds a custom agent or automation around the member’s actual workflow.','Reusable lessons can improve the wider SOS product while preserving appropriate client boundaries.'],perry:'Provides strategic context only when the workflow touches core Perry principles.',team:'Discovery, mapping, agent design, integrations, testing, documentation, and optimization.',feeds:'Operational proof, reusable features, Enterprise work, and T1C opportunities.'},
    {title:'Farm Builders & Small-Group Leaders',sub:'Power users who contribute back.',icon:'compass',simple:'Advanced users become contributors, facilitators, and small-group leaders—earning status by implementing, helping, and improving the system.',bullets:['Contribution and real implementation matter more than passive membership.','Choose the leader first, then the city.','Tier 3 and Tier 4 members become the leadership pool for national chapters.'],perry:'Opens or closes selected experiences and sets the cultural standard.',team:'Training, facilitator systems, chapter playbooks, performance tracking, and support.',feeds:'The Farmhouse, Tier 5 expansion, and ecosystem leadership.'}
  ]},
  {id:'tier4',label:'Tier 4',sub:'The Farmhouse',color:'#d946ef',glow:'rgba(217,70,239,.09)',summary:'The ultimate goal: founders calm the operational chaos first, then earn access to high-level mindfulness, intellectual, and strategic retreats with Perry.',nodes:[{title:'Mindfulness & Strategic Retreats With Perry',sub:'Elite founder access after the systems are working.',icon:'crown',simple:'Private experiences for advanced founders focused on thinking, strategy, spirituality, leadership, legacy, and the questions Perry actually wants to explore.',bullets:['Direct Perry time is intentionally concentrated here.','Participants arrive prepared because lower tiers handled the fundamentals and operational chaos.','Premium rooms can include outside experts and curated peer groups.'],perry:'The central thinker, retreat leader, and high-level strategic presence.',team:'Selection, preparation, logistics, experience design, follow-up, and continuity.',feeds:'Legacy work, premium client relationships, investment opportunities, and Tier 5 leaders.'}]},
  {id:'tier5',label:'Tier 5',sub:'National Expansion',color:'#37e8a0',glow:'rgba(55,232,160,.08)',summary:'A brotherhood/fraternity-style chapter model expands The Farm into new cities through proven Tier 3 and Tier 4 leaders—not by dropping pins on a map.',nodes:[{title:'Chapter Expansion',sub:'Austin, Miami, Nashville, and beyond.',icon:'map',simple:'Chicago proves the model. Proven leaders then open new chapters with a repeatable event, community, service, diagnostic, and SOS playbook.',bullets:['Choose the leader first, then the city.','Local chapters preserve the culture while creating regional business value.','Expansion uses the same media, membership, service, diagnostic, and software engines.'],perry:'National authority, occasional launch moments, and standards.',team:'Chapter licensing, training, playbooks, technology, launch campaigns, audits, and support.',feeds:'National network, sponsors, events, services, and future Perry-level founders.'}]}
];
const timelineData=[
  ['Months 1–3','Phase 1 — Build the Media Engine & Academy','$60,000 front-loaded. Build The $1 Million Idea Search, PM in the AM, the man-on-the-street contest videos, EM:Dirt academy, Pocket AI, campaign assets, web/data capture, and Chicago infrastructure.'],
  ['Months 4–6','Phase 2 — Run the Chicagoland Search & Beta','Run ads for the free $1 Million Idea Search for three months, release the Phase 1 contest videos, measure lead generation, find 10 Chicagoland business owners, retarget the lead pool with EM:Dirt, and document real use.'],
  ['Months 7–9','Launch Tier 1 + Install Tier 2','Scale the improved EM:Dirt offer, activate the Farm community and T1C services, sell the $497 diagnostic, and onboard founding SOS users at $97 for the first year.'],
  ['Months 10–12','Tier 3 Builders, Farmhouse & Expansion','Launch the $297/month SOS Builder tier with custom onboarding AI agents, train Farm Builders, create premium Perry experiences, and prepare chapter expansion.']
];
const roles=[
  ['Phase 1','Perry records authority, core teaching, and selected campaign moments.','Team builds the academy, contest videos, media engine, content bank, funnels, data capture, AI, and campaigns.'],
  ['Phase 2','Perry supplies authority, selected founder interactions, and standards for the 10 businesses.','Team runs three months of ads, publishes the contest videos, captures leads, selects and onboards the cohort, retargets EM:Dirt, and reports results.'],
  ['Tier 1','Perry lends IP, authority, and selected appearances.','Team runs the accelerator, community, events, services, follow-up, and fulfillment.'],
  ['Tier 2','Perry sets diagnostic and operating-system principles.','Team operates the diagnostic, builds SOS as a Business Operating System, manages onboarding, workflows, automations, analysis, and reporting.'],
  ['Tier 3','Perry supplies strategic context and cultural authority.','Team builds custom onboarding AI agents, the dev community, advanced SOS, contributor rewards, and leaders.'],
  ['Tier 4','Perry leads the premium retreats and intellectual work.','Team selects, prepares, produces, and supports the experience.'],
  ['Tier 5','Perry remains the national authority.','Team creates chapter systems, technology, launch campaigns, training, and quality control.']
];
const monetizationData=[['B2B Sponsorships','dollar','The $1 Million Idea Search and PM in the AM can attract corporate sponsors at approximately $35–$75+ CPM, plus custom integrations.','Sponsors','Perry ecosystem','Production and sales','Funds media while extending reach.'],['Dynamic Ad Insertion','mic','Current ecosystem promotions can be inserted into Perry’s historical audio and video back catalog.','Advertisers / internal offers','Perry ecosystem','Ad operations','Turns old attention into current demand.'],['The 20% Vault','vault','$19–$49/month private RSS feed for raw voice memos, economic breakdowns, and unfinished thinking.','Subscribers','Perry','Light editing / delivery','Monetizes the ideas that do not need a full course.'],['Affiliate Tech Stack','tools','SOS can recommend approved tools with 20%–40% recurring commissions.','Software partners','Agreed ecosystem economics','Curation / support','Adds recurring revenue while helping members implement.']];